Adjust sync committee size and duration
ethereum/eth2.0-specs pull request #2371
Opened 2021-05-01 23:32 UTC by ralexstokes

If we merge #2370 then we will also want to tune the sync committee parameters to be friendly to light clients (including bridges, etc.) while still maintaining a floor for security.

2021-05-04 18:22 UTC, djrtwo reviewed
Need to adjust or remove the sync protocol value I mentioned below

2021-05-04 18:22 UTC, djrtwo commented on configs/mainnet/altair.yaml
> +EPOCHS_PER_SYNC_COMMITTEE_PERIOD: 512
We need to force `LIGHT_CLIENT_UPDATE_TIMEOUT` to be equal to the sync committee period.

Tbh, might jsut remove `LIGHT_CLIENT_UPDATE_TIMEOUT` and just use `EPOCHS_PER_SYNC_COMMITTEE_PERIOD` in it's place

2021-05-04 20:50 UTC, ralexstokes commented
@djrtwo good catch on the `LIGHT_CLIENT_UPDATE_TIMEOUT`, i've addressed that concern and a few other minor things in #2378.

that PR should be merged along w/ this one

2021-05-05 12:41 UTC, hwwhww approved these changes

2021-05-05 12:41 UTC, hwwhww commented on specs/altair/beacon-chain.md
> +| `EPOCHS_PER_SYNC_COMMITTEE_PERIOD` | `Epoch(2**9)` (= 512) | epochs | ~54 hours |
```suggestion
| `EPOCHS_PER_SYNC_COMMITTEE_PERIOD` | `uint64(2**9)` (= 512) | epochs | ~54 hours |
```

2021-05-05 12:56 UTC, Ariya383323 commented on configs/mainnet/altair.yaml
>  # 2**6 (= 64)
A

2021-05-05 12:57 UTC, Ariya383323 commented on configs/mainnet/altair.yaml
> +SYNC_COMMITTEE_SIZE: 512
A

2021-05-05 12:59 UTC, Ariya383323 requested changes
I-Level

2021-05-06 18:50 UTC, merged