small Altair cosmetic fix for consistency
ethereum/eth2.0-specs pull request #2473
Opened 2021-06-08 15:23 UTC by JustinDrake

for consistency with `process_randao`, `process_eth1_data`, `process_operations` which take `state` and `block.body` as inputs

2021-06-08 15:35 UTC, protolambda requested changes
Please don't, randao and and eth1 data processing were a big oversight IMHO. We should aim to encapsulate changes to the state as much as possible. There is no reason to inject the whole beacon block body into this function, and with every hardfork that changes the body type structure, clients will have trouble updating this function.

2021-06-08 15:39 UTC, hwwhww commented
I think the problem was how to align the test format and what's the definition of "operation". 
- [`sync_aggregate` is considered as "operations" in test format](https://github.com/ethereum/eth2.0-specs/blob/c821e3fced725995242e12037ad9ce502d5b2208/tests/formats/operations/README.md#condition). `process_sync_aggregate` is similar to `process_SSZ_CONTAINER(state, SSZ_CONTAINER)` functions  like `process_attestation(state, attestation)`.
- Currently, `process_operations(state: BeaconState, body: BeaconBlockBody)` only process "a List of operations".

Since renaming `process_operations` is not phase0 backward compatible, alternatively, I'd say we can consider moving `process_sync_aggregate` into `process_operations`.

related issue: #2433

2021-06-15 09:59 UTC, JustinDrake commented
I would have closed this issue based on Proto strong opinion (I don't care too much 😂 ).

@hwwhww: It sounds like you're in a position to make some sort of informed opinion regarding tests, `process_block` versus `process_operations`, etc. Assigning this issue to you—feel free to close if that's the right action :)

2021-08-11 17:07 UTC, djrtwo commented
closing this  as is
some additional convo going on in #2506

2021-08-11 17:07 UTC, closed without merging